//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalInstitution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatient
    {
        public int PatientID { get; set; }
        public string PatientNameSurname { get; set; }
        public string JMBG { get; set; }
        public string HealthInsuranceCardNumber { get; set; }
        public string UsernameLogin { get; set; }
        public string PasswordLogin { get; set; }
        public Nullable<int> Doctor { get; set; }
    
        public virtual tblDoctor tblDoctor { get; set; }
    }
}
